spring:
  # 数据库配置项
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.166.43:3306/slam?characterEncoding=utf-8
    username: root
    password: Zhh1156@

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.azhe.lulutong.VO

logging:
  level:
    com.azhe.lulutong.mapper: debug